### ISSUE TITLE
Error message on submitting loss brought forward

### ISSUE THREAD

**Issue by johnhemming** [hmrc/individual-losses-api#147]
I am getting this error:
{"code":"RULE_INCORRECT_OR_EMPTY_BODY_SUBMITTED","message":"An empty or non-matching body was submitted"} 

When I submit this body
{"lossAmount":123.45,"selfEmploymentId":"XEIS70071313266","typeofLoss":"self-employment","taxYear":"2018-19"}

Could you please give me a hint as to where this is going wrong.

**Comment by mtd-api-team** [comment]
Hi @johnhemming,

It looks like you just have a small typo in the `typeOfLoss` field.

Its great that you are starting to test against these endpoints, however you may find that over the next week or so the endpoints become unavailable again for a short time.  This is due to an internal quality assessment we will be putting the API through, so don't be alarmed if you get responses saying the API is unavailable for a short time.

If you need anything else, don't hesitate to get in touch.

The MTD API team

**Comment by johnhemming** [comment]
Thanks for your help with this.  I now get:
The response from HMRC follows:
id: AAZZ1234567890a

**Comment by johnhemming** [comment]
I have now linked to my system the creation of loss claims and losses, listing of those, getting those and amendment of those.  I will stop working on this now as it is essentially usable and it has been said that this will be subject to breaking changes.  Hence I will come back to it when it get close to going into production (or slightly after that).

**Comment by mtd-api-team** [comment]
Brilliant @johnhemming, I'm glad you've managed to hook up to it so quickly.  We wouldn't expect too many major changes.  

In the near future you may see the inclusion of HATEOAS links, which can optionally be used by consumers to navigate the APIs.

We welcome feedback on what is in place at the moment, and if what is there works for you.

Regards,
The API team.
